#  
## Introduction: 

The purpose of this thesis is to use musical stylometry to quantify the difference between the compositions of the siblings Felix and Fanny Mendelssohn. (I hate starting things help...)

Treating text or music as data has challenges. Neither contains anything immediately analyzable. With the increasing availability of the internet and social media data, text classification has become an promising form of data analysis. While text classification problems are very frequent, similar methods that classify music have not been as commonly explored. To explore these problems, first analyzable features must identified that can be extracted for every text. These features can include word frequencies, length etc.  Analysis of text using machine learning can find patterns, authors, or categories of text. Similar methods can also be used to classify music.

Musical stylometry is ...

Feature extraction is an essential part in text or music classification. Unlike in a data set of numerical or categorical values, text and music must first go through a processing stage where features of interest can be extracted before any models can be fit. 

For music, the extracted features are used to build a model that can correctly classify a likely composer for that piece of music. Studies that examine the style of a type of music or composer are known as musical stylometry studies. For musically trained humans, this might be an easy task. Some are able to automatically distinguish a piece composed by Bach or Mozart either by listening to a recording, or looking at sheet music.  This becomes more difficult when composers are contemporaries. Mozart and Salieri might be distinguishable to a more discerning listener or scholar, but it might be harder. Harder still is when the identity of the composer piece of music is disputed. Examples of such disputed authorship exist throughout music history, most notably in the Renaissance.  

In both text and music classification, we must create features that can be calculated that would give a signal to indicate some conscious or unconscious tendency of the composer that would make them distinguishable. 


<!--- ================================================================ -->
<!--- ================================================================ -->
<!--- ================================================================ -->
## Brief history of text classification

The Federalist Papers were one of the earliest instances of text classification for determining authorship.[@mosteller1964inference]. The famous Federalist Papers were written under the pen name 'Publius'. There are several of these disputed papers attributed to James Madison or Alexander Hamilton. The authors never admitted authorship, as some of the writings were contradictory to their later political positions [@adair1944]. Prior to quantitative analysis, historians had often examined the papers using styles of previously known writings of Madison and Hamilton. Their analysis was often partially based on the content of the letters, for example the existence of citing English history is a trait more common to Hamilton. [@authorshipfed] 

In contrast, Mosteller and Wallace (1964) used the frequency of words such as 'and', 'by', 'from', and 'upon', to train the writings on a set of known writings by each author. These unconscious indicators were able to differentiate between the two writers, and the model was able to identify the likely author of the disputed paper.

<!--- ================================================================ -->
<!--- ================================================================ -->
## Feature selection

Text analysis, such as in the Federalist Papers, is accomplished by reading one word after another. Information in a piece of music, however, is read in a variety of ways. It can be read left to right note by note, but it can also be read vertically as the harmony, or the notes played together. Also in a piece with several instruments, the above happens at the same time for each instrument. There are also aspects that take place over large sections, such as phrasing, or cadential patterns. There are rules of counterpoint that are followed throughout the entire piece. Thus we need to find features that can be measured for each piece, or perhaps each measure or instrument, that can describe a certain piece of music. Then we must decide which features are those of rules and practices of classical music, and where the creativeness and individuality of a composer happens. As there are many different aspects of a piece, melodic changes, harmonies, etc, one can end up with many features to describe one piece. It is possible that the number of predictors $(p)$ can be greater than the sample size $(n)$, or that many features encode essentially the same thing. We thus need to figure a clever way to decrease our predictor space. This can happen in choosing what features we want to use to model, or using a dimension reduction technique such as PCA. 

Most of the classical musical stylometry papers have focused on composers in the Renaissance(1400-1600), Baroque(1600-1750), and Classical(1730-1820) eras. The Mendelssohns were composing in the Romantic era(1780-1910). The focus of earlier papers may have been because composers in earlier eras followed rules of counterpoint more exactly, or perhaps had less "expressive" allowances for their composing, thus making features easier. There are also more pieces with doubtful authorship in those eras. In addition Computer Assisted Research in the Humanities (CCARH) has a large corpus of encoded music from these times. As will be described later, the initial step of coding the music is the most time consuming, having music in a format immediately conducive to analysis is very helpful.

<!--- ================================================================= -->
## A Very Short Introduction to Music Theory

Western sheet music is presented on a five line staff. The sound of a note depends on its pitch, which is a specific vibration of sound waves at a certain frequency. The vertical distance between notes (also known as an interval) depends on how many half steps occur between two notes. There are 12 half steps in the western scale. Melodic intervals are defined as the number of half steps between two adjacent notes. Harmonic intervals are defined as the number of half steps between notes played at the same time. Chords occur when there are more than two notes being played simultaneously. The type of chord is also determined by the harmonic intervals it contains. Cadences are a type of chord progression, usually occurring at the end of a phrase and especially at the end of a piece. Musical notes are in the set $\text{note} \in \{A,B,C,D,E,F,G\}$. The value of a note can be changed up or down a half step, by adding a sharp or flat. The key signature of the piece indicates how many sharps or flats are normal for the piece. A piece's key can be major or minor, although the piece can internally modulate between the two. The scale degree of a note depends on its position of the key that it is in. The time signature of a piece determines the number of beats that are in each measure. Intervals and chords can be either dissonant or consonant. Consonant intervals sound nice to our ears, whereas dissonant intervals add a sense of tension or unease, which is used to shape the feel of the music. In addition chords and intervals can be minor or major. Minor intervals feel "sad", whereas major intervals feel "happy". These are also known as sonorities, and divided into three types. Imperfect sonorities are... perfect sonorities are ... and and dissonant sonorities are.. 

For classical music there are some "rules" that most composers follow to some extent. These were followed more strictly in the Baroque era than the Romantic era. These rules are known as counterpoint. First species counterpoint is a type of counterpoint. One rule is that there are no parallel perfect consonances. Perfect consonances are octaves, fourths and fifths. Parallel indicates that they occur one after another. Another rule is that from one perfect consonance to another, the notes must proceed in contrary or oblique motion. 


<!--- ================================================================= -->
<!--- ================================================================= -->
## Musical features

Features calculated from music often closely follow music theory. In music, in addition to deciding the features, there is also the decision of the scope at where those features take place. They can be features for a given instrument, the entire piece, or each measure. Also windowing techniques can be used where a "window" is created over a given number of bars or notes, and shifts across the whole piece For each window, a feature is recorded. These can be overlapping windows by creating an "offset" of a number of beats or notes. Windowing produces more data, as instead of one feature for each piece, there is a feature for each window.

Musical features are often thought about as either high level, or low level. While the exact definition of each often varies, low level is often understood to be features such as note frequency, etc. High level features are more about a broader sense of the piece, including chord progressions, etc. High level features are often what music experts use in their analysis, whereas low-level features are more easily done with computer analysis. High level features often depend on the context of where the features was extracted from. For example, cadences and modulations (brief changes in key) throughout the piece are easily found when a human analyzes a piece of music, but are very hard to generalize as a feature. If one wants to use high-level features, they would first have to train the feature to see if it was performing accurately. For this reason, this paper focuses only on low level pieces, or pieces that are context independent. 

Especially in research regarding text categorization, data sets have enormous numbers of variables. We use "feature" and "variable" interchangeably, with the exception when features are created from variables, and the distinction will be made in that case [@guyon2003]. There are several variable selection algorithms that select the "important" variables that could be included in models. If one included every variable that was extracted from a piece, the model would very likely be overfit. Thus some feature selection is important before fitting a model. 


<!--- ================================================================= -->
<!--- ================================================================= -->
## Background on Variable and Feature Selection

Before analysis is done or models are fit, numerous features are often extracted from the music without knowing a priori which ones will be helpful in identifying a composers' style. Fitting models with all of the features that are available can often lead to overfitting of the model. There are three main ways to deal with this problem: subset selection, shrinkage models, and dimensionality reduction. This section gives a broad overview of options for features selection. The methods chosen to be used in this thesis will be described in further detail in chapter 4. 

Subset selection methods choose which features to use in a model. There are many ways to do this and existing feature selection algorithms can help with this process. One idea to see which features are best for the model is to look at all possible subsets of the variables and see which model preforms best. All possible subsets of variables is $2^p-1$, where $p$ is the number of features. For large $p$, this is often computationally impossible. Instead of fitting all possible subsets, strategies like best-first, branch and bound, simulated annealing, and genetic algorithms can help with the computational difficulties. 

Subset selection methods often use some sort of variable ranking tool to determine which variables are useful to include in the best subset. Variable ranking uses a score function to assign a score to each possible variable. It is a computationally efficient method and is robust against overfitting as it introduces bias but may result in less variance. It is tempting to only include variables that have a high score. However, this possibly leads to redundancy. In addition, variables that are not important by themselves can have a significant performance improvement when considered with other variables. Single variable classifiers rank the variable according to its individual predictive power. The predictive power can be measured in terms of error rate, or using the false positive or false negative rate. This classifier cannot distinguish variables that perfectly separate the data. 

Shrinkage methods, instead of pickig which features to use, use all $p$ features in the model. They instead use techniques that constrain the coefficient estimates of the model used. Ideally, coefficients of features that are not as useful for the model will be shrunk towards zero, so they do not have a large effect on the model. Constraining features in this way often leads to a reduction in variance. The most common shrinkage methods are ridge regression and the lasso. 

The two methods mentioned above, shrinkage methods and subset selection both use the original variables. Dimension reduction methods transform the features space, and then fit models on the transformed variables. It is commonly used to combine enough of the information given in the features in a smaller dimensional space. This results in feature creation; using the recorded variables to create new features to fit the model on. Common dimension reduction techniques include Principal components analysis(PCA) and linear discriminant analysis (LDA). Goals of feature creations include that we can achieve a good reconstruction of the data and that we can be successful in making our predictors.

<!--- ================================================================= -->
<!--- ================================================================= -->
## Previous research. 

There have been numerous other applications of machine learning to music. These include many studies that are not specifically identifying a composer from sheet music. For example, a previous study used machine learning trained on a composer's music to have the computer learn the style and compose a piece in a similar style. [@papadopoulosai]

Research on musical stylometry has focused on two types of data: audio and sheet music. This analysis uses data in the form of sheet music. To predict a composer, a training data set of pieces of known composer is needed. Then a model can be fit to a testing data set to predict composer. If the fitted model shows good predictions, that model can be used on the pieces of unknown authorship. Musical stylometry can be used to resolve disputed authorship, but also to detect distinguishing musical styles of composer, even if there are no disputed pieces. This same process can also be used to look at the development of a composers musical style over time. 

This paper draws its inspiration from four different studies that have looked at the question of classifying composers by extracting features from sheet music. Initial studies in the 1970's started looking at ways to represent music in a way that could analyzed by computers. Recently, several previous papers have focused on Josquin des Prez. This is likely due to the fact that there is a large training and testing data set available in easily analyzable format provided by the Josquin Research Project [@jrp]. In addition there are a number of pieces of disputed authorship that have been attributed to him. 

Work by Brinkman et al. [@brinkman2016] uses machine learning to evaluate attribution of compositions by Josquin des Prez. They first compared music of Josquin and JS Bach's four part chorales. Many listeners could easily distinguish these two composers as they were separated by two centuries. They also compared Josquin to composers closer in time and style: Ockeghem and Du Fay, who are only one or two generations separated. These composers could likely be differentiated by experienced listeners of Renaissance music. Finally they compared Josquin's to his contemporaries: de Orto and La Rue to find differences in style. 

Work by Backer et. al.(2005) looked at differences in style between J.S. Bach, Telemann, Handel,Haydn and Mozart and then examined a disputed piece: BWV 534 which is believed to be composed by J.S. Bach, J.L. Krebs, or W.F. Bach (J.S. Bach's son). [@backer2005] 

The following two studies to not try to identify composers of unknown works, but instead try to fit classfiers that can correctly predict composers based on differences in style. 

Crerar [@crerar] used incipits from Vivaldi, Correlli, and Valentini, who could have been a student of Correlli. They used low level features, especially looking at intervalic movement. They also compared Bach, Haydn, and Mozart.

Mearns et. al. [@mearns2010] extrected high level musical features on J.S. Bach, Buxtehude, Ruggero, Vivaldi, Monteverdi, Corelli, and Frescobaldi. The idea was that they all adhered to the laws of counterpoint, and that they possibly still had distinct uses of the counterpoint. They used pieces across instrumental genres with the idea that stylistic counterpoint would remain constant across compositional type. 



<!--- ================================================================= -->
<!--- ================================================================= -->
## Previous choices of features in applications

Deciding on and extracting features of music is the first step of analysis. Depending on the characteristics of the composer and time period different features would be useful. Often features are extracted en masse and then work is done later to determine which features are important or useful in identifying style. 

In addition to what kinds of features, there is also the question of the scale of those features. They can be features for a given instrument, the entire piece, or each measure. Also windowing techniques can be used where a "window" is created over a given number of bars or notes, and moves through the whole piece. For each window, a feature is recorded. These can be overlapping windows by creating an "offset" of a number of beats or notes. This produces more data, as instead of one feature for each piece, there is a feature for each window, and there can be tens of windows in each piece. 

Common types of features used before in music analysis are: Frequencies or fractions of notes, chords, etc. are a common low-level feature. These include the fraction of the score that consisted of dissonant sonorities, as well as the fraction of bars that begin with a dissonant sonority. Other features include the type of intervals or consonances present in a piece: perfect consonance, imperfect consonances, and dissonance. In polyphonic pieces, the four types of motion, (parallel, similar, oblique, and contrary) can also be used as features. Crerar [@crerar] used pitch frequencies, after standardizing all pieces by transposing to the key of C, the first melodic interval of the piece, and note transition counts. 

Features measuring "stability" are also popular. Stability is computed by dividing the standard deviation of the lengths of the fragment by the mean length of the fragments. It is normalized in this way to be comparable over differing time signatures.  These types of features were used by Backer et. al.[@backer2005]. They also used overlapping windowing over each entire composition to produce more data. They chose a window of 30 bars to create a high enough number of fragments per piece and a low enough variance of the feature values between fragments. They chose to extract 20 features including features of fractions and measuring stability, and entropy. They computed the entropy of the probability of occurrence chords. They measured this two different ways, defining chords to be the same no matter what scale degree they are on, and distinguishing chords differently depending on scale degree. Next the entropy was calculated given the probability of each pitch in the score. Entropy was calculated by $-\sum_{i = 1}^{N}p_i\log{p_i}$ where $p_i$ is the probability of occurrence, and $N$ is the total number. Next they the calculated average number of active voices at one time which represents the voice density of the piece. Then for every interval, the duration of that interval was divided by the total duration of all intervals. Next the total duration of parallel thirds, fourths, and sixths divided by the total duration of all intervals was measured. Finally a measure of suspensions was found.

Brinkman et.al [@brinkman2016] used both high-level and low-level features. The high level features were 9-8 suspensions, oblique motion, contrary motion, similar motion and parallel motion. The low level features were average melodic entropy, normalized pairwise variability index, and note-to-note transition probabilities. 


Other features that can be helpful for distinguishing Renaissance and Baroque composers look specifically at differences in counterpoint. Since most composers in that era generally followed the rules of counterpoint, these features are created to try to detect specific identifiable uses of counterpoint. These features include counterpoint movement types, dissonance distributions, parallel intervals of each kind, and vertical interval distributions. Mearns used such features [@mearns2010]. They calculated intervals for every subsequent pitch in each part. A weighted count of each interval was stored. They were weighted according to duration to account for the perception of use. The count vector was then normalized to account for the weighted interval content of the score. For movement types, they used ideas based on the rules of first species counterpoint. (Similar, oblique, parallel, and contrary). It does not make musical sense to compare every single adjacent group of notes. Many of the note groups occurring at fractional metrical positions consist of notes held from the previous note group with the addition of a passing or neighbor note in another voice or voices. For this reason, only notes that occur at strong metrical positions, in this case on each beat of the bar, are used for contrapuntal evaluation. This is a relatively simplistic method of choosing structurally important notes. In Bach, for example, the majority of voice progressions take place at a closer level. The features for counterpoint method include the nature of the approach to a perfect consonance, whether a dissonance is properly prepared (i.e. preceded by a consonant interval containing the same note which then becomes dissonant), whether a dissonance is correctly resolved downwards by step, details of parallel intervals, and the overall distribution of contrapuntal movements (oblique / contrary / similar / parallel / other). A feature for total vertical interval count is also used.

<!--- ================================================================= -->
<!--- ================================================================= -->
## Previous modeling in applications

Most of the previous research has needed to do some kind of feature selection. Usually features are extracted before any analysis is done, and we dont know before hand which features are distinguishing. 


A modification of a forward selection (Floating Forward Selection [@pudil1994floating] was used in Backer's (2005) study to extract features in order to identify distinguishing style between Bach, Handel, Telemann, Mozart, and Haydn, and then subsequently classify the authorship of BWV 535. Each composer was compared via creating comparisons of all possible class arrangements, ie (Bach)(Handel), (Bach)(Handel,Teleman), etc. The algorithm extracted features for each class arrangement that distinguished the groups the best. A $k$-nearest neighbors classifier was fit using the features that the subset selection algorithm found useful. The model  was successful in comparing Bach and others as well as each individual composer. The $k$-nearest neighbor classifier resulted in a leave-one-out-error of between 5% and 9%, for most class arrangements, and 24.3% between Hayden and Mozart, Decision trees were also used to interpret the features used in decision making of the different class arrangements. The decision trees used between 2 and 4 features depending on which class comparison was being analyzed. It resulted in a max of one classification error. To determine authorship of BWV 535, quadratic Bayesian classifier was trained to distinguish J.S. Bach, W.F. Bach and J.L Krebs. They again compare every possible class arrangement as potential composers. Their results showed that BWV 535 was likely composed by either W.F. Bach and his pupil, J.L. Krebs.

Principal components analysis (PCA) was used for dimension reduction for subsequent analysis on the music Josquin and his contemporaries. [@brinkman2016] Binary comparisons were used to compare composers. Although only two principal componentss accounted for most of the variance, in the comparison between Bach and Josquin, five principal components were used to account for more variance (85%). Between Josquin and his contemporaries, 27 principal components were used to account for 85% of the variance.  This resulted in a relatively clear separation between Bach and Josquin when visualized on thier first two prinicpal components. Between Josquin and each of his contemporaries, the principal components did not have as much of an obvious seperation. The transformed features from principal components analysis were used to train a classifier. First a $k-$nearest neighbor classifier was used with $k = 6$. The training set consisted of 80% of the data, with 20% witheld as a testing set. The model correctly predicted pieces de Orto 38.9% of the time, Josquin 60.6%, La Rue, 80.6% Next they trained a support vector machine classifier, which preformed similarly to the $k-$nearest neighbor classfier. 


Mearns fit a classifier using a WEKA algorithm, as well as Naive Bayes and a Decision Tree was created that correctly predicted composer 2/3 of the time. [@mearns2010]

Crerar [@crerar] took a different approach, and instead of trying to fit a model that would classifty composers, preformed a chi-squared test to see if the groups were in fact different. This would imply that the composers had different styles that could be distinguised using the features in the paper. The probability of the chi-squared values occuring were all less thatn 0.05, and thus the composers do indeed have different styles. 

<!--- ================================================================ -->
<!--- ================================================================ -->
<!--- ================================================================ -->
<!--- ================================================================ -->
## Fanny and Felix Mendelssohn

Most musical stylometry analysis has focused on music of the Renaissance and Baroque period, as there are more questions of authorship in that period. As the Romantic period is much more modern in comparison, there are many more surviving records of original manuscripts that include the composer. 

Felix Mendelssohn, often considered a prodigy akin to Mozart, was a prolific composer. Before he was fourteen years old, he had already written over 100 compositions. 

His lesser known sister Fanny Hensel née Mendelssohn was also a composer of incredible skill. The two were very close, for many years training and studying together. In their early education living in Berlin, Felix and Fanny received the same musical education, first piano lessons by Madam Bigot, a famous pianist esteemed by Haydn and Beethoven. Beginning in 1818, Carl Friedrich Zelter, a somewhat removed student of Bach and the most influential Berlin musician of the time, began to teach them both composition. In addition to music, the children were tutored by some of the finest scholars in Berlin in subjects such as languages, history, and drawing. Goethe himself claimed that Fanny was "as gifted as Felix" [@tillard1996].

As Fanny grew up, her father started implying that she should focus her energy on the domestic sphere of her life. While the fact that she never became a world famous composer and performer is often attributed to the gender politics of her time, it is also likely due to her high class. [@reich1991] Especially considering the anti-Semitic feelings of the time, and since the family had recently converted from Judaism to Christianity, the family did not want any other unusual characteristic such as a professional female composer to set them further apart from "polite" society. 

Most of Fanny's available work are lieder, short pieces of voice accompanied by piano. They were accepted at the time as the more feminine, domestic compositions, acceptable for women to compose. Her brother moved on to more elaborate compositions such as operas, orchestral concertos and symphonies. Her father pressured Fanny to remain composing Lieder. [@todd2003]

> "Music will perhaps become his profession, while for you it can and must only be an ornament, never the root of your being and doing. We may therefore pardon him some ambition and desire to be acknowledged in a pursuit which appears very important to him,… while it does you credit that you have always shown yourself good and sensible in these matters; … Remain true to these sentiments and to this line of conduct; they are feminine, and only what is truly feminine is an ornament to your sex."

Throughout their lives, Felix and Fanny maintained contact through letters until Fanny's death in 1847 and Felix's death shortly thereafter. These letters contain many instances of Felix asking for advice on his compositions. 

Unlike Felix who conducted and performed piano and organ in some of Berlin's most esteemed concert halls, most of Fanny's performances were private, only performed in small circles of her friends and family at intimate parties. Similarly, although she was quite a prolific composer, under recommendation of her father Abraham Mendelssohn, and to a lesser extent Felix, Fanny did not publish her work until later in her life. In 1846 after her father's death and though her brother disapproved, she published her first collection of Lieder. Many of Fanny's unpublished notebooks are in private collections and are inaccessible for study.

However, it is widely speculated that some of Fanny's work was published under her brother's name, especially three pieces each in his Op 8 and 9 lieder. 

Famously, when Felix met the Queen of England, she sang Felix's lied "Italien", and Felix had to admit that in fact, it was his sister that had written it. In a letter to Felix, Fanny admits: 

> "I have just recently received a letter from Vienna, which contained basically nothing but the question of whether “On Wings of Song” was by me, and that I should really send a list of things that are running about in the world disguised, it seems that they aren’t clever enough themselves to separate the wheat from the chaff." [@mace2013]

As she never made such a list, we are left to wonder if there are any other pieces of hers that have been published under her brothers name and reputation. It is suspected that most of Fanny's friends and family would have known at the time that she had composed the pieces published by felix. An article written in the Harmonicon in 1830, an influential music journal in London, mentioned that all the lied in Felix's collection were not written about him: 

> " I possess twelve published songs under Mr. Mendelssohn's name, which he wrote when a boy of fifteen. One of these appears in the musical annual, “Apollo's Gift,” and deserves all the praise you have in your review bestowed on it. But the whole of the twelve are not by him: three of the best are by his sister, a young lady of great talents and accomplishments. I cannot refrain from mentioning Miss Mendelsshon's name in connexion with these songs, more particularly when I see so many ladies without one atom of genius, coming forward to the public with their musical crudities, and, because these are printed, holding up their heads as if they were finished musicians. Miss Mendelssohn is a first-rate piano-forte player, of which you may form some idea when I mention that she can express the varied beauties of Beethoven's extraordinary trio in Bb, beginning She has not the wild energy of her brother; but possesses sufficient power and nerve for the accurate performance of Beethoven's music. She is no superficial musician; she has studied the science deeply, and writes with the freedom of a master. Her songs are distinguished by tenderness, warmth, and originality: some which I heard were exquisite."[@harmonicon]

This project will use lieder of Fanny and Felix Mendelssohn. Most of the available work by Fanny are lieder, of which Felix also composed a great deal. We will see if there is a determinable difference in style of these siblings who grew up very close and received mostly the same musical education. All other previous composership studies cannot be adjusted for training and upbringing, so it might be challenging to detect a difference. 






