# Conclusion {-}

Fitting classifiers using low-level features composed mostly of frequencies of notes and rhythms was able to differentiate style between Bach and Fanny and Felix Mendelssohn. However classifiers using these low-level features were not successful in differentiating between Fanny and Felix. Of the ten models fit on pieces by Fanny and Felix, only 4/10 did better than random guessing. The $k-$nearest neighbor classifier and lasso logistic performed the best. Thus the low-level features used in this study were not able to measure style differences between Fanny and Felix. This is likely either to the fact that these features were not able to pick an existing signal, or that Fanny and Felix have no discernible difference in style, although the first is more likely. Most of the previous studies regarding composer identification were able to distinguish composer. The work by Brinkman when comparing Josquin to contemporaries did have substantial error in , although not as bad . Josquin and his contemporaries however, did not grow up together or receive identical music training, like Fanny and Felix did. Also analyzing music in the Romantic era has not been done before, and perhaps different kinds of features need to be created to train a successful classifier. 


## Future suggestions for research and expansion of museR

Most suggestions for future work lie in expanding the capabilities for museR. One issue to be improved upon is increasing the ease of importing data. The scanning/OMR step is incredibly time consuming, which lead to a limited number of pieces being used in this analysis. Running this same analysis with more data would also be good. While museR cannot directly help with speeding up the scanning process, museR could be expanded to be able to import music in the musicXML format in order to not need to rely on Humdrum's conversion program. Future versions of museR will ideally be able to extract high level features. These are features that take into account the context of the music from where the feature is extracted. These features could include more harmonic features, such as chord progressions, and more chord analysis. These high level features are what humans generally pick up on when distinguishing style. In addition, in the future, museR should be able to implement windowing techniques for extracting features. These features could still be low-level features, but they might have more meaning in determining style as they are on a smaller scale instead of averaged across the entire piece. 

In addition, it would be interesting to perform this same analysis on music of different different types of pieces.  We might expect unconscious signals to exist in the same way in symphonies as well as lieder, or perhaps not. Considering features that are similar between symphonic work and solo piano works is a challenging problem in of itself. Also including another composer in this study, perhaps a contemporary of Felix and Fanny, or at least a composer in the Romantic era would also be helpful in checking the validity of the features. Also it would be interesting to examine composers throughout their career. Composers, Dvorak for example, changed drastically their career.  Maybe they had different aspects when they first started composing than when they were older. Ideally museR could be used to pick up on these differences. 





