---
title: "Interval functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

## R Markdown

```{r}

notes_to_val <- function(note){
  if(str_detect(note, "[Aa]-")){
     v <- "A flat"
  } else if(str_detect(note, "[Aa]$")){
     v <- "A"
  } else if (str_detect(note, "[Aa]#")){
    v <- "A sharp"
  } else if (str_detect(note, "[Bb]-")){
    v <- "B flat"
  } else if (str_detect(note, "[Bb]$")){
    v <- "B"
  }else if (str_detect(note, "[Bb]#")){
    v <- "B sharp"
  } else if (str_detect(note, "[Cc]-")){
    v <- "C flat"
  }  else if (str_detect(note, "[Cc]$")){
    v <- "C"
  } else if (str_detect(note, "[Cc]#")){
    v <- "C sharp"
  } else if (str_detect(note, "[Dd]-")){
    v <- "D flat"
  } else if (str_detect(note, "[Dd]$")){
    v <- "D"
  } else if (str_detect(note, "[Dd]#")){
    v <- "D sharp"
  } else if (str_detect(note, "[Ee]-")){
    v <- "E flat"
  } else if (str_detect(note, "[Ee]$")){
    v <- "E"
  } else if (str_detect(note, "[Ee]#")){
    v <- "E sharp"
  } else if (str_detect(note, "[Ff]-")){
    v <- "F flat"
  } else if (str_detect(note, "[Ff]$")){
    v <- "F"
  } else if (str_detect(note, "[Ff]#")){
    v <- "F sharp"
  } else if (str_detect(note, "[Gg]-")){
    v <- "G flat"
  } else if (str_detect(note, "[Gg]$")){
    v <- "G"
  } else if (str_detect(note, "[Gg]#")){
    v <- "G sharp"
  } else
    v <- note
  }
}





```