---
title: "Log-10-2"
output: github_document
---

### Research Log

Thesis mtg: 

* Working on coding muse data in R - is there a better way to do this? 
* Much of the muse data seems like it will be unnesecary for analysis. I think I only need the first four collumns


This week I:

* Read about Muse Data
* Installed and read about Humdrum
* Started figuring out how to use Humdrum
* Decided its better to make my own R script
* Worked on getting my script running - in progress 




To do for next week!: 
* Figure out how muse data is made
* ask about finale 
* object oreinted prog R 
* google if anyone has done musical analysis R packages
* figure out humdrum 
* Email john - figure out musical question - which corpus 
* Code up some objects and think about formats
* Email Anderw brinkman - it looks like you did analysis in R, coudl you share code? 


Objects : Muse - list       corpus- list    dataframe --- data frame



mehtods - functions to use on obmects 
        - feature_extraction()
        - create_df()


create_df(corpus,reponse = "", features = c(function names))

ask at thesis mtg: 
- How do you create a package within a project? 



carver choir book -  
eaton "" 


diamm 








